empPrj/empApp/urls.py
from django.urls import path
from . import views

app_name='empApp'

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    # path('list/',views.EmployeeListView.as_view(),name='list'),
    path('create/',views.EmployeeCreateView.as_view(),name='create'),
    path('update/<int:pk>',views.EmployeeUpdateView.as_view(),name='update'),
    path('list/<str:department_slug>/',views.employee_list,name='emplist_by_department'),
    path('show/',views.employee_list,name='list'),
    path('delete/<int:pk>',views.EmployeeDeleteView.as_view(),name='delete'),

]

empPrj/empPrj/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from empApp import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomeView.as_view(),name='home'),
    path('emp/',include(('empApp.urls','app_name'),namespace='employee')),
    path('util/',include(('utilApp.urls','app_name'),namespace='util')),
    path('',include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

empPrj/utilApp/urls.py
from django.urls import path
from . import views

app_name='utilApp'

urlpatterns = [
    
     path('sendmail/',views.SendEmailwithAttachment,name='sendmail'),
    # path('delete/<int:pk>',views.EmployeeDeleteView.as_view(),name='delete'),

]

empPrj/empApp/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Department(models.Model):    
    id=models.AutoField(primary_key=True)
    name=models.CharField('Depatment Name',max_length=100)
    slug=models.SlugField(max_length=150,unique=True,db_index=True,blank=True)
   
    def __str__(self) -> str:
        return f'{self.name}'
        # return f'{self.id} {self.name}'

    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug=slugify(self.name)

        return super().save(self,*args, **kwargs)


    def get_absolute_url(self):
       
        return reverse('employee:emplist_by_department', args=[self.slug])    



class Employee(models.Model):    
    id=models.AutoField(primary_key=True)
    name=models.CharField('Employee Name ',max_length=100)
    email=models.EmailField('E-mail Address ',unique=True,blank=True)
    dob=models.DateField('Birth Date Fld ',default=timezone.now,blank=True,help_text='Format: yyyy-mm-dd')    
    salary=models.DecimalField('Monthly Salary ',max_digits=8,decimal_places=2,blank=True,null=True)
    photo=models.FileField(upload_to='myimage',default='myimage/blank.png',blank=True)
    department=models.ForeignKey(Department,on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.id} {self.name}'

empPrj/utilApp/models.py
from django.db import models

# Create your models here.

empPrj/empApp/forms.py
from django import forms
from django.forms import fields
from .models import *

class DepartmentForm(forms.ModelForm):
    class Meta:
        model=Department
        fields='__all__' 


class EmployeeForm(forms.ModelForm):
    class Meta:
        model=Employee
        fields='__all__'      

empPrj/utilApp/forms.py
from django import forms

class EmailForm(forms.form):
    email=forms.EmailField(max_length=100)
    subject=forms.CharField(max_length=100)
    message=forms.CharField(max_length=200)
    attach=forms.FileField(required=False)
    

empPrj/empApp/views.py
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse_lazy
from .models import *
from .forms import *
from django.views.generic import *
from django.urls import reverse
from django.contrib import messages

# Create your views here.


class HomeView(TemplateView):
    template_name = "home.html" 


# class EmployeeListView(ListView):
#     model = Employee
#     template_name = "emp/list.html"
#     # paginate_by=2


class EmployeeCreateView(CreateView):
    model = Employee
    template_name = "emp/empForm.html"
    form_class=EmployeeForm

    def get_success_url(self):
        messages.success(self.request,'Data Inserted Successfully...')
        return reverse('employee:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] ='Create' 
        context["heading"] ='Create New Employee' 
        return context

    

class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = "emp/empForm.html"
    form_class=EmployeeForm
    # success_url=reverse_lazy('employee:list')

    def get_success_url(self):
        messages.success(self.request,'Data Updated Successfully...')
        return reverse('employee:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Edit'
        context["heading"]='Update Employee'
        return context
    

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = "emp/delete.html"
    form_class=EmployeeForm

    def get_success_url(self):
        messages.success(self.request,'Data Deleted Successfully...')
        return reverse('employee:list')


def employee_list(request,department_slug=None):
    department=None
    departments=Department.objects.all()
    employees=Employee.objects.all()
    if department_slug:
        department=get_object_or_404(Department,slug=department_slug)
        employees=Employee.objects.filter(department=department)
        
    context={'department':department,'departments':departments,'object_list':employees}
    return render(request,'emp/list.html',context)
        

empPrj/utilApp/views.py
from django.shortcuts import render

# Create your views here.
def SendEmailwithAttachment(request):
    if request.method=='POST':
        pass
    else:
        pass

    context={}
    return render(request,'mail/mailform.html',context)

empPrj/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock%}</title>
    <link rel="shortcut icon" href="{%static 'img/favicon.ico' %}" type="image/x-icon">
    <!-- Font Awesome -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
        />
        <!-- MDB -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
        rel="stylesheet"
        />
         <!-- datepicker -->
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

         <!-- Data Table -->
         <link rel="stylesheet" href="https://cdn.datatables.net/1.11.1/css/jquery.dataTables.min.css">
    {% block stylesheet %}{% endblock%}
</head>
<body>
    <div class="container">
        <header>
            <div>
                <img src="{%static 'img/logo.png'%}" alt="" width="100%">
            </div>
            <div>
                <nav class="navbar navbar-expand-lg navbar-light bg-">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#"><img src="{%static 'img/favicon-32x32.png'%}" alt=""></a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{%url 'home'%}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'employee:list' %}">Employee</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <li><a class="dropdown-item" href="#">Action</a></li>
                              <li><a class="dropdown-item" href="#">Another action</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                          </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                          
                          {% if request.user.is_authenticated %}
                          <li class="nav-item">
                            <a href="#" class="nav-link">Hi! {{ request.user.username }} </a>
                          </li>
                          <li class="nav-item">
                            <a href="{% url 'logout' %}" class="nav-link">Log Out </a>
                          </li>
                            {% else %}
                            <li class="nav-item">
                              <a href="{% url 'login' %}" class="nav-link">Login </a>
                            </li>
                            <li class="nav-item">
                              <a href="#" class="nav-link">Register </a>
                            </li>
                          {% endif %}
                            

                        </ul>
                        <!-- <form class="d-flex">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form> -->
                      </div>
                    </div>
                  </nav>
            </div>
        </header>
        <main >
          <div class="container">
            <br>
           
            
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              
            {% endfor %}
              
            {% block content %}{% endblock%}
          </div>
            
        </main>
    </div>
   <!-- MDB -->
        <script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
        ></script>
        <!-- jquery -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- datepicker -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <!-- Data Table -->
        <script src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js"></script>
     {% block javascript %}{% endblock%}
     <script src="{% static 'js/myScript.js' %}"></script>
</body>
</html>

empPrj/templates/emp/delete.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %}
    
{% block content %}


<form  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <!-- <div class="modal" tabindex="-1" role="dialog" id="myModal" > -->
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete Employee</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Are you sure You Want to Delete?</p>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Confirm Delete</button>
              <a href="{% url 'employee:list' %}" class="btn btn-warning">Back to list</a>
            </div>
          </div>
        </div>
      </div>
   
   
        
{% endblock  %}
        

empPrj/templates/emp/empForm.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %}
    
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
   <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header bg-primary text-white" >
                    <p class="p-2"> {{ heading }} </p>                  
                </div>
                <div class="card-body">
                    {% load crispy_forms_tags %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{% url 'employee:list' %}" class="btn btn-warning"> Back </a>


                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <p class="p-2"> ... </p>                  
                </div>
                <div class="card-body">
                    <img src="{{ object.photo.url }}" alt="" width="300px" class="blah" >
                </div>
            </div>
        </div>
   </div>
</form>
{% endblock content %}

empPrj/templates/emp/list.html
{% extends 'base.html' %}


{% block title %}{{ title }}{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-3">
        <ul>
            <li class="list-unstyled"><a href="{% url 'employee:list' %}">All</a></li>
            
            {% for dept in departments %}
                <li class="list-unstyled"><a href="{{ dept.get_absolute_url }}">{{ dept.name }}</a></li>
            {% endfor %}
                

        </ul>
    </div>
    <div class="col-sm-9">
        <form action="" method="POST">
            {% csrf_token %}
            <a href="{% url 'employee:create' %}" class="btn btn-primary">Add New Record</a>
            <hr>
    
            <table class="table table-striped" id="emptable" data-page-length="2">
                <thead>
                    <tr>
                        <th>Employee ID</th>
                        <th>Employee Name</th>
                        <th>Email Address</th>
                        <th>Date Of Birth html</th>
                        <th>Salary</th>
                        <th>Photo</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for emp in object_list %}
                        <tr>
                            <td>{{ emp.id }}</td>
                            <td>{{ emp.name }}</td>
                            <td>{{ emp.email }}</td>
                            <td>{{ emp.dob|date:'Y-m-d' }}</td>
                            <td>{{ emp.salary }}</td>
                            <td><img src="{{ emp.photo.url }}" alt="" width="100px"></td>                           
                                
                            <td>
                                
                                <a href="{% url 'employee:update' emp.id %}" class="btn btn-warning"><i class="fas fa-edit fa-lg" ></i> Edit </a>
                                <a  href="{% url 'employee:delete' emp.id %}"  class="btn btn-danger"><i class="fas fa-trash fa-lg" ></i>  </a>
                 
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="7" class="text-center bg-warning">No Record Found</td>
                        </tr>
    
                    {% endfor %}
                        
    
                </tbody>
                <tfoot>
    
                </tfoot>
            </table>
            <!-- <nav aria-label="Page navigation">
                <ul class="pagination pagination-circle ">
                    
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">&laquo;</a>
                        </li>    
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
                        </li>
                    {% endif %}
                        
                        {% for i in page_obj.paginator.page_range %}
                            
                            {% if page_obj.number == i %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{ i }}</a>
                                </li>
                            {% else %}
                                <li class="page-item" aria-current="page">
                                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                </li>
                            {% endif %}
                                
                        {% endfor %}
    
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1" aria-disabled="true">&raquo;</a>
                        </li>    
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a>
                        </li>
                    {% endif %}    
                        
                        
                  
                  
                </ul>
              </nav> -->
        </form>    
    </div>
</div>
    
{% endblock content %}
    
    

    
    

empPrj/templates/home.html
{% extends 'base.html' %}

{% block title %}{{title}}{% endblock title %}
    
{% block content %}
    <div class="jumbotron" >
            <h1 class="display-4">
                Home Page
            </h1>
            <p class="lead">
                Web Application Development Using Django
            </p>
            <hr class="my-4"> 
            <p>Python Batch 6 </p>
            <a href="#" class="btn btn-primary btn-lg">Learn More </a>
    </div>
   
{% endblock content %}